apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: init
        image: alpine
        command: ['sh', '-c', 'wget -O /deployments/keycloak-metrics-spi.jar https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.4.0/keycloak-metrics-spi-2.4.0.jar && touch /deployments/keycloak-metrics-spi.jar.dodeploy']
        volumeMounts:
          - mountPath: /deployments
            name: deployments
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:15.0.0
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: KEYCLOAK_STATISTICS
          value: "all"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          value: "acid-minimal-cluster:5432"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak.acid-minimal-cluster.credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak.acid-minimal-cluster.credentials
              key: password
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/deployments/
          name: deployments
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
      volumes:
      - name: deployments
        emptyDir: {}
