apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
spec:
  selector:
    matchLabels:
      app: keycloak-mgmt
  endpoints:
  - port: mgmt
    path: /metrics
