apiVersion: v1
kind: Service
metadata:
  name: keycloak-mgmt
  labels:
    app: keycloak-mgmt
spec:
  ports:
  - name: http
    port: 9990
    targetPort: 9990
  selector:
    app: keycloak
  type: ClusterIP
