apiVersion: v2
name: loki
description: Loki Logging Stack
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: loki-stack
  version: 2.6.5
  repository: https://grafana.github.io/helm-charts
