loki-stack:
  loki:
    persistence:
      enabled: "true"
      size: "20Gi"
      storageClassName: "local-path"
    serviceMonitor:
      enabled: "true"
      additionalLabels:
        release: "monitoring"
  promtail:
    enabled: "true"
    extraScrapeConfigs:
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'
    # Mount journal directory into promtail pods
    extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
    extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
