apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - deployment-keycloak.yaml
  - ingress-keycloak.yaml
  - namespace-keycloak.yaml
  - podmonitor-postgresql-exporter.yaml
  - postgresql-acid-minimal-cluster.yaml
  - service-keycloak.yaml
  - servicemonitor-keycloak-metrics.yaml
