apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

bases:
  - https://raw.githubusercontent.com/istio/istio/release-1.13/samples/addons/jaeger.yaml

resources:
  - ingress-jaeger.yaml
