apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - https://raw.githubusercontent.com/istio/istio/1.21.0/samples/addons/jaeger.yaml
  - ingress-jaeger.yaml
