apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    appgroup: system
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/monitoring
    repoURL: https://github.com/dgo19/k3s-demo.git
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
      env:
        - name: OPTIONS
          value: --include-crds
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
