apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-bookinfo
  namespace: argocd
  labels:
    appgroup: servicemesh
spec:
  destination:
    namespace: istio-bookinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/istio-bookinfo
    repoURL: https://github.com/dgo19/k3s-demo.git
    targetRevision: HEAD
