apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    appgroup: system
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/loki
    repoURL: https://github.com/dgo19/k3s-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
