apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.3.1
    helm:
      parameters:
      - name: loki.persistence.enabled
        value: "true"
      - name: loki.persistence.size
        value: "20Gi"
      - name: loki.serviceMonitor.enabled
        value: "true"
      - name: loki.serviceMonitor.additionalLabels.release
        value: 'monitoring'
      - name: loki.persistence.storageClassName
        value: "local-path"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
