apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system-jaeger
  namespace: argocd
  labels:
    appgroup: servicemesh
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/istio-system-jaeger
    repoURL: https://github.com/dgo19/k3s-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
