apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/falco
    repoURL: https://github.com/dgo19/k3s-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
