---
- name: install additional packages (debian family)
  become: yes
  become_user: root
  apt:
    force_apt_get: yes
    pkg:
    - git
    - curl
    - apache2-utils
    - ansible
  when: ansible_os_family == "Debian"
- name: install additional packages (redhat family)
  become: yes
  become_user: root
  yum:
    name:
    - git
    - curl
    - perl-Apache-Htpasswd
    - ansible
    state: present
  when: ansible_os_family == "RedHat"
