apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-pipelines

bases:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.35.1/release.yaml

configMapGenerator:
  - name: config-registry-cert
    namespace: tekton-pipelines
    behavior: replace
    files:
      - cert=ca.crt
