apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/zalando/postgres-operator/manifests?ref=v1.5.0

namespace: postgres-operator

resources:
  - namespace-postgres-operator.yaml
