apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=controller-v0.45.0

namespace: ingress-nginx

secretGenerator:
  - name: tls-secret
    namespace: ingress-nginx
    files:
      - tls.crt
      - tls.key
    type: Opaque

patches:
   - deployment-ingress-nginx-controller.yaml

generatorOptions:
  disableNameSuffixHash: true
