ingress-nginx:
  controller:
    hostNetwork: true
    extraArgs:
      default-ssl-certificate: ingress-nginx/tls-secret
      enable-ssl-passthrough: ""
    kind: DaemonSet
    service:
      enabled: true
      type: ClusterIP
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
