starboard-operator:
  operator:
    replicas: 1
    # leaderElectionId determines the name of the resource that leader election
    # will use for holding the leader lock.
    leaderElectionId: "starboard-operator"
    # vulnerabilityScannerEnabled the flag to enable vulnerability scanner
    vulnerabilityScannerEnabled: true
    # configAuditScannerEnabled the flag to enable configuration audit scanner
    configAuditScannerEnabled: true
    # kubernetesBenchmarkEnabled the flag to enable CIS Kubernetes Benchmark scanner
    kubernetesBenchmarkEnabled: true
    # batchDeleteLimit the maximum number of config audit reports deleted by the operator when the plugin's config has changed.
    batchDeleteLimit: 10
    # batchDeleteDelay the duration to wait before deleting another batch of config audit reports.
    batchDeleteDelay: 10s
  # service only expose a metrics endpoint for prometheus to scrape,
  # starboard-operator does not have a user interface.
  service:
    type: ClusterIP
    metricsPort: 80
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
  rbac:
    create: true
  serviceAccount:
    # Specifies whether a service account should be created.
    create: true
    annotations: {}
    # name specifies the name of the k8s Service Account. If not set and create is
    # true, a name is generated using the fullname template.
    name: ""
  
  podAnnotations: {}
  
  podSecurityContext: {}
    # fsGroup: 2000
  
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
