apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-nginx-dev

resources:
  - namespace-test-nginx-dev.yaml
  - pipeline-kaniko-pipeline.yaml
  - pipelinerun-test-nginx.yaml
  - sealedsecret-registry-auth.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.5/kaniko.yaml
