apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  pipelineRef:
    name: kaniko-pipeline
  params:
    - name: git-url
      value: https://github.com/dgo19/k3s-demo-test-nginx
    - name: git-revision
      value: main
    - name: image-name
      value: registry.registry.svc.cluster.local:5000/test/test-nginx:latest
    - name: path-to-image-context
      value: ./
    - name: path-to-dockerfile
      value: ./Dockerfile
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: dockerconfig
      secret:
        secretName: registry-auth
