kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test-nginx-build
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
