# kubectl -n test-nginx-dev create secret generic registry-auth --from-literal=config.json="{\"auths\":{\"registry.registry.svc.cluster.local:5000\":{\"username\":\"registry\",\"password\":\"password\",\"auth\":\"$(echo -n 'registry:password' | base64 -w0)\"}}}" -o yaml --dry-run | kubeseal --cert https://sealed-secrets.k3sdemo.lan/v1/cert.pem -o yaml > sealedsecret-registry-auth.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-auth
  namespace: test-nginx-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  encryptedData:
    config.json: AgAwHCx2cCc1Y5tvnfd6qpK2CaJq4gcAjU/GRK8PjRUvDy0q3ggyb7cKdijl6VlY9pL5tgWLKnQmcW4QVaMJxfNDtfepTjOfXGe1K20jZDFZ3m0MIyuGuZS/na1vRqe49D/iejNiXbh1sbGW4LlEiqVFWWye+a9zy7cCQK2DQBdLzXI9sKeY+IzOv5vN0ru2/uGQnV1l4BV2HDl/UEOB9zL4i5PMzHo8mInd9H852nHcpYzGbiEhGzf7ZPHzEcoZfKZUmiemE6vlgxSNvYinjLRMEdAmoXBiAnXim3x+OTdPU+1McevEJyhuT/uAG8wuJaznXLT84mhcGYMEbRSQKBG38ITQ5Al3Z0ubxtvcqVWAIEzo1UteEu1kBEW9oCDJKuMe0Hb7dmIzOymVNTc5wC9RTdupZEHcErRYvpMPKYn+qxvTAPdladUgMtDDu9DVMWFMJ6K4UYLN6ZuWP7C3FfP2WXmBv6tj22EFFRXiEeei8yHC4OU6btX5yUZ9LcOv4jq8sehcbDpyCqT3YepuM/oy8RXCxsEsTtzK9Hni5sGa3nhhl6CWZroHdb0tg0RwzbVlVt8QgbiuwKu9GFKuNrl1mO314oTOtoHeFRMg/4Gh9uychUpBvv3KuXecx9Js+tizI715wcpZvTWvnNPA7mwDRb3Aj5QrF0GW/20VO1/GnlWSxcI2n3RRYeq7q2IYrCmR95BaEqCwwj9BJD+GzCsvgD1jRkfXiOjl4DpHnUPkSG/4wsREsqqMIN86JNtlCML/uIumKFi+lY1z3/uZZGiVEDoWe98FmbSoNOzkjq3bQERNg36Hc50riSL+11poOYyEiG/cTn1235rzJs7skxeiRFKIM6MCiqN9UHUl1EDTnn18De0D0Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-auth
      namespace: test-nginx-dev
