apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gogs

resources:
  - ingress-gogs.yaml
  - namespace-gogs.yaml
  - sealedsecret-gogs-setup.yaml
  - service-gogs.yaml
  - statefulset-gogs.yaml

configMapGenerator:
  - name: gogs-conf
    files:
      - app.ini

generatorOptions:
  disableNameSuffixHash: true
