apiVersion: v1
data:
  secret.createSecret: "false"
  application.instanceLabelKey: "argocd.argoproj.io/instance"
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template $ARGOCD_ENV_OPTIONS --release-name $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE . > all.yaml && kustomize build"]
kind: ConfigMap
metadata:
  name: argocd-cm

