apiVersion: v1
data:
  secret.createSecret: "false"
  repositories: |
    - name: dgo19-k3s-demo
      type: git
      url: https://github.com/dgo19/k3s-demo.git
    - name: grafana
      type: helm
      url: https://grafana.github.io/helm-charts
    - name: prometheus-community
      type: helm
      url: https://prometheus-community.github.io/helm-charts
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template $OPTIONS --release-name $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE . > all.yaml && kustomize build"]
kind: ConfigMap
metadata:
  name: argocd-cm

