apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.7

namespace: argocd

configMapGenerator:
  - name: argocd-ssh-known-hosts-cm
    behavior: replace
    files:
      - ssh_known_hosts

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - secret-argocd-secret.yaml

resources:
  - ingress-argocd.yaml
  - namespace-argocd.yaml
  - sealedsecret-argocd-secret.yaml
  - sealedsecret-repo-dgo19-k3s-demo.yaml
  - secret-repo-helm-aquasecurity.yaml
  - secret-repo-helm-grafana.yaml
  - secret-repo-helm-istio-release.yaml
  - secret-repo-helm-kiali.yaml
  - secret-repo-helm-ingress-nginx.yaml
  - secret-repo-helm-prometheus-community.yaml
  - servicemonitor-argocd-metrics.yaml
  - servicemonitor-argocd-server-metrics.yaml
  - servicemonitor-argocd-repo-server-metrics.yaml

generatorOptions:
  disableNameSuffixHash: true
