# created by kubectl -n argocd create secret generic repo-dgo19-k3s-demo --from-literal=type=git --from-literal=url="https://github.com/dgo19/k3s-demo.git" --dry-run=client -o yaml | kubeseal --cert https://sealed-secrets.k3sdemo.lan/v1/cert.pem -o yaml > sealedsecret-repo-dgo19-k3s-demo.yaml
# add label argocd.argoproj.io/secret-type: repository to tmeplate
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-dgo19-k3s-demo
  namespace: argocd
spec:
  encryptedData:
    type: AgBVSdscRO7pmD8/qwryrI8+QZ6MBOlQFZN68urCXnltjyBl4jtIiH4F8FCkGe5z61Yqi/mmn4n4/Jpk/2Au+J2kUrtNjrUVo4PNiMcEJztcpKx/OLvG+RwZdTUKK9fWVo7w3Mhm6drKEUgtvy1iWz/nGVdezHExLiOuZzPihvehunF9L8J3J2w5CfWCvHYvA8Gj887S5rVxTwckpA/lsejAb2OT2gc/08OSBgdOUzih/2PLIAjBX5iCfOKKii9KcJaJTCXqqWO1ZuHcoK7xVMdIdiF5YjZTks0LpKfhobJrJ5noVFnZxHEJyZbdKmx+mFm/7VAAM3GJ+NAy+m8niUs55JiNCqM5bXJHIjs38IRvZM5FvHC/NIDXuplVD7AN2cLzJABmtfValUaaeZdLBFVqgAazKqle0wLee3OpLiBonFl2aekp8CezB99t69B7ZCRxLq40bb6JslmpdVMH/pJOtTqyVCxYHa1inGJT4tsCNjNConKPSw0/IKl2fqVustr+0n7NJ3ZC4/amGXJsUDlBW5ylsliXd9sfU8WkNBrROg4KGPjr+YPbBfSTJY4GINd4imGb1KGPeM0uhUI9kD5Vhi94P/pw0BXVvR/cjqJ1ApvAnUtFPW5y7hPza4l0K57ZD6qdTWWXBcVbaajkjZciu1yK/4InGL2ArHCuPAt7gWRFzWoBCDqXLibK3Ng1LtgzxpE=
    url: AgCeyflTluWm5Wo6DfPi2CdU8He0NMk0sjcdFPVGC/UqBUALx5BTM0DYgEOqlkwsBwuUtpyE+WKPdtAmOrnrTRw0czYmtrUPorlHbntiqMP/1TCvNb56iXEwQbfTpCl57nk6GWYpFQNeCEvcQp+/C2kpwP1tUWCsRp8D3h96KQ+wEdtr4dOlfDBQdKjk0l5Xz+LeozHj8Y8LUX5/lRj0F9tSYjaEIL+BOLzfQj557cRUxZzKwWpi5fexCsc4XdKF+B3x0oi6+G1sXm/v8wbOLL8xdGS4md2rlzzV4n5LsKP/OM4vhFG+GgEPaLD5d1cK6akPxl9DcKIOP6SpE2/u/e6Mqof6OFub8ANXBbA54hQGqfRrMeIUqB/vo9ZLjq7oCAmm6gjWOOXf/HX1gnfR2fJ/xGgjdgaLMIPPMoHvTmcVwUcLVrNr85HJXCChk12N5Shkou78adYTDQf27wEm3DfmeSkyjiv160wzXhRD9GyWASPYOK19V/IElEk9d5c4IHJ0t/K+SGAJ+OwFhdJynCcEuu4suib/MzaQzYS5LdLsaUbBLhJUE/LRW25pbSUb3pEDEmVhRqH2E0zzX0I/pcdMD9qKOiAEX3J52F2eCgTpByvg+s/DFuEcCNOMyM/jcHjsh6AEYx0PZEcUy/cEl0719uH0CxIxyEpAx1VKOSxZxKVMc2dXzZcEjnwH8bEY/56btrgmDtGbAYe2j7H1FtulcdNdUTPMJcjXvW63+iECyL75tEYo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: repo-dgo19-k3s-demo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
