apiVersion: v1
data:
  type: aGVsbQ==
  url: aHR0cHM6Ly9raWFsaS5vcmcvaGVsbS1jaGFydHM=
kind: Secret
metadata:
  creationTimestamp: null
  name: repo-helm-kiali
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
