apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-bookinfo

resources:
  - namespace-istio-bookinfo.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.12/samples/bookinfo/platform/kube/bookinfo.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.12/samples/bookinfo/networking/bookinfo-gateway.yaml
