apiVersion: v2
name: istio-system
description: Istio
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: base
  version: 1.12.1
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: 1.12.1
  repository: https://istio-release.storage.googleapis.com/charts
- name: gateway
  version: 1.12.1
  repository: file://gateway
  #repository: https://istio-release.storage.googleapis.com/charts
- name: kiali-server
  version: v1.43
  repository: https://kiali.org/helm-charts
