global:
  # Used to locate istiod.
  istioNamespace: istio-system
gateway:
  name: "istio-ingressgateway"
  replicaCount: 1
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: NodePort
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 30080
      protocol: TCP
      targetPort: 80
    - name: https
      port: 30443
      protocol: TCP
      targetPort: 443
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: ""
kiali-server:
  auth:
    strategy: anonymous
  deployment:
    ingress:
      enabled: false
      class_name: "nginx"
    view_only_mode: false
  external_services:
    prometheus:
      url: "http://monitoring-kube-prometheus-prometheus.monitoring:9090/"
    tracing:
      enabled: true
      in_cluster_url: 'http://tracing.istio-system:16685/jaeger'
      use_grpc: true
      # Public facing URL of Jaeger
      url: 'https://jaeger.k3sdemo.lan/'
    grafana:
      enabled: true
      in_cluster_url: "http://monitoring-grafana.monitoring:80/"
      url: "https://grafana.k3sdemo.lan/"
  login_token:
    signing_key: "secret:kiali-signing-key:key"
  server:
    web_fqdn: "kiali.k3sdemo.lan"
    web_root: "/"
