gateway:
  name: "istio-ingressgateway"
  replicaCount: 1
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: LoadBalancer
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 30080
      protocol: TCP
      targetPort: 80
    - name: https
      port: 30443
      protocol: TCP
      targetPort: 443
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: ""
kiali-server:
  deployment:
    ingress:
      enabled: true
  external_services:
    prometheus:
      url: "http://monitoring-kube-prometheus-prometheus.monitoring:9090/"
    tracing:
      enabled: false
    grafana:
      enabled: true
      in_cluster_url: "http://monitoring-grafana.monitoring:80/"
      url: "https://grafana.k3sdemo.lan/"
  login_token:
    signing_key: "secret:kiali-signing-key:key"
  server:
    web_fqdn: "kiali.k3sdemo.lan"
    web_root: "/"
