# created by running kubectl -n test-nginx create secret docker-registry registry-k3sdemo-lan --docker-server=registry.k3sdemo.lan --docker-username=registry --docker-password=password --docker-email="" -o yaml --dry-run | kubeseal --cert https://sealed-secrets.k3sdemo.lan/v1/cert.pem -o yaml > sealedsecret-registry-k3sdemo-lan.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-k3sdemo-lan
  namespace: test-nginx
spec:
  encryptedData:
    .dockerconfigjson: AgAx8ArTa+APAh6SUZqrHoRsxsmFooQsbu5O3Ou71IPIgK72H18++j0mBTZmHSaRA6+y/qVCuE2Pm4NRGpRQmtH4cN3Jp7wA+cofApSWjoUh51O5zwjFXYk7jas3ScAYVZQCmN8mPhnl2B/2bRKkoze//m87fS0PgYqHm/6KXftFx5K+G9piKAVEWNgTqmSu6gY4p7CwXJdVFA/FYL1FJeof4C8jGTG4iFXLsrwc1wAjaOnlXrdi82LX8vNJDQ6ASfId8V4iU8NcbrTNyVxdFJ28JiOAY1X6p7t92+Iwosrc4J7HaPsbRhomW4K5Q32YfcykXIJaUgdMizT5E11d/zpsw/Zc7Yz9JAPVXxuU7N0oZq9IzjQXxejiddKyPK0hX0xr0WT7zuqfDE+WW10X62XROF6xA0bD+nd7gfOVeTbZe0hSnM8XY/tlk/8E2I5DdtwVTE+PDxU/6HT3fni0N/ND7yd3E6jgHO4+5x7ARP9HHJ/n843ZSQWQIKg1ExsrbskJM5zlRzsez9lM9LvnY1vVR8mmLFtikVtTjCzha14ZaANLWJkqP4D5w+rtvBLufdVmDBKzC3UtzgKawOwTxJSWCpyKLBQUtKTNVazvkJdOtTk0Y6CmoXEPswXIHhOIcomg7Ab/RJbbArslgahaCFfLEnFopOzKO7/LQAG+kg/re1loV5GDMYfDLt6kqqdd6fbwd0xRFSam1gFjjAug8gt33gMRmioYu8fQEdbw51Z9/j0IyijRE2+UiZUjTgPLPcVwluUM47jcg2fbbkMxHwLaDI6yFN6DI+cJpKBhBtIEvUODRGZu5SXFYzgOjlnO6yZdjA/W6jACbL3s2tGXBQpIBMU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: registry-k3sdemo-lan
      namespace: test-nginx
    type: kubernetes.io/dockerconfigjson
