apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-configmap-web
spec:
  rules:
  - host: configmap-web.microk8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: configmap-web
            port:
              number: 80
