apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: configmaps

resources:
  - deployment-configmap-web.yaml
  - ingress-configmap-web.yaml
  - namespace-configmaps.yaml
  - service-configmap-web.yaml

configMapGenerator:
  - name: nginx
    literals:
      - my-var1=test
      - my-var2=two
    files:
      - index.html=index.html

generatorOptions:
  disableNameSuffixHash: true
