apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb-pv

resources:
  - statefulset-mariadb-pv.yaml
  - deployment-phpmyadmin.yaml
  - ingress-phpmyadmin.yaml
  - namespace-mariadb-pv.yaml
  - sealedsecret-mariadb-secret.yaml
  - service-mariadb.yaml
  - service-phpmyadmin.yaml

configMapGenerator:
  - name: mariadb-conf
    literals:
      - mysql-database=testdb
  - name: phpmyadmin-conf
    literals:
      - pma-host=mariadb

generatorOptions:
  disableNameSuffixHash: true
