apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

bases:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.0/controller.yaml

patchesStrategicMerge:
  - deployment-sealed-secrets-controller.yaml

resources:
  - ingress-sealed-secrets.yaml
